package View;

import controller.ClienteController;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.DAO.ClienteDAO;
import model.VO.ClienteVO;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author turma.310157
 */
public class CadastroClienteGUI extends javax.swing.JDialog {

    String nome;
    String cpf;
    String rg;
    String telefone;
    String endereco;
    int idEditar = 0;

    /**
     * Creates new form CadastroCliente
     */
    public CadastroClienteGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        setLocationRelativeTo(null);
        lbObrigatorioNome.setVisible(false);
        lbObrigatorioCpf.setVisible(false);
        lbObrigatorioRg.setVisible(false);
        lbObrigatorioTel.setVisible(false);
        lbObrigatorioEndereco.setVisible(false);

    }

    public CadastroClienteGUI(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();

        ClienteDAO cliente = new ClienteDAO();
        ClienteVO clienteAdd = cliente.selecionarCliente(id);

        if (clienteAdd != null) {

            idEditar = id;
            jLabel1.setText("Editar Cliente");
            btncadastrar.setText("Editar");
            setLocationRelativeTo(null);
            lbObrigatorioNome.setVisible(false);
            lbObrigatorioCpf.setVisible(false);
            lbObrigatorioRg.setVisible(false);
            lbObrigatorioTel.setVisible(false);
            lbObrigatorioEndereco.setVisible(false);

            jTextNome.setText(clienteAdd.getNome());
            jTextrg.setText(clienteAdd.getRg());
            jTexttelefone.setText(clienteAdd.getTelefone());
            jTextcpf.setText(clienteAdd.getCpf());
            jTextendereco.setText(clienteAdd.getEndereco());

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbObrigatorio4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNome = new javax.swing.JTextField();
        jTextendereco = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btncadastrar = new javax.swing.JButton();
        btnlimpar = new javax.swing.JButton();
        lbObrigatorioNome = new javax.swing.JLabel();
        lbObrigatorioCpf = new javax.swing.JLabel();
        lbObrigatorioRg = new javax.swing.JLabel();
        lbObrigatorioEndereco = new javax.swing.JLabel();
        lbObrigatorioTel = new javax.swing.JLabel();
        jTextcpf = new javax.swing.JFormattedTextField();
        jTextrg = new javax.swing.JFormattedTextField();
        jTexttelefone = new javax.swing.JFormattedTextField();

        lbObrigatorio4.setForeground(new java.awt.Color(204, 0, 0));
        lbObrigatorio4.setText("*");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Clientes");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/folder-customer-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextNome.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N

        jTextendereco.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jLabel3.setText("CPF:");

        jLabel4.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jLabel4.setText("RG:");

        jLabel5.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jLabel6.setText("Endereço:");

        jLabel7.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 12)); // NOI18N
        jLabel7.setText("Telefone:");

        btncadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/salvar.png"))); // NOI18N
        btncadastrar.setText("Cadastrar");
        btncadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncadastrarActionPerformed(evt);
            }
        });

        btnlimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/limpar.png"))); // NOI18N
        btnlimpar.setText("Limpar");
        btnlimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimparActionPerformed(evt);
            }
        });

        lbObrigatorioNome.setForeground(new java.awt.Color(204, 0, 0));
        lbObrigatorioNome.setText("*");

        lbObrigatorioCpf.setForeground(new java.awt.Color(204, 0, 0));
        lbObrigatorioCpf.setText("*");

        lbObrigatorioRg.setForeground(new java.awt.Color(204, 0, 0));
        lbObrigatorioRg.setText("*");

        lbObrigatorioEndereco.setForeground(new java.awt.Color(204, 0, 0));
        lbObrigatorioEndereco.setText("*");

        lbObrigatorioTel.setForeground(new java.awt.Color(204, 0, 0));
        lbObrigatorioTel.setText("*");

        try {
            jTextcpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTextrg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jTexttelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnlimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btncadastrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextNome)
                            .addComponent(jTextendereco, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
                            .addComponent(jTextcpf)
                            .addComponent(jTextrg)
                            .addComponent(jTexttelefone))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbObrigatorioNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbObrigatorioCpf, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbObrigatorioRg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbObrigatorioTel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbObrigatorioEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btncadastrar, btnlimpar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lbObrigatorioNome, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lbObrigatorioCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbObrigatorioRg, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextrg, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextendereco, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addComponent(lbObrigatorioEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(lbObrigatorioTel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTexttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncadastrar)
                    .addComponent(btnlimpar))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btncadastrar, btnlimpar});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimparActionPerformed

        limpar();

    }//GEN-LAST:event_btnlimparActionPerformed

    private void limpar() {
        jTextNome.setText("");
        jTextrg.setText("");
        jTexttelefone.setText("");
        jTextcpf.setText("");
        jTextendereco.setText("");

        lbObrigatorioNome.setVisible(false);
        lbObrigatorioCpf.setVisible(false);
        lbObrigatorioRg.setVisible(false);
        lbObrigatorioTel.setVisible(false);
        lbObrigatorioEndereco.setVisible(false);
    }


    private void btncadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncadastrarActionPerformed
        ClienteController cliController = new ClienteController();

        cliController.cliente.setNome(jTextNome.getText());
        cliController.cliente.setCpf(jTextcpf.getText());
        cliController.cliente.setRg(jTextrg.getText());
        cliController.cliente.setTelefone(jTexttelefone.getText());
        cliController.cliente.setEndereco(jTextendereco.getText());
        cliController.cliente.setNome(jTextNome.getText());
        cliController.cliente.setCpf(jTextcpf.getText());
        cliController.cliente.setRg(jTextrg.getText());
        cliController.cliente.setTelefone(jTexttelefone.getText());
        cliController.cliente.setEndereco(jTextendereco.getText());

        if (idEditar == 0) {

            verificaCamposEmpty();
            dispose();
        } else {
            cliController.editar(cliController.cliente, idEditar);
            dispose();
        }

    }//GEN-LAST:event_btncadastrarActionPerformed

    public void salvar() {
        ClienteController controller = new ClienteController();

        controller.cliente.setNome(jTextNome.getText());
        controller.cliente.setCpf(jTextcpf.getText());
        controller.cliente.setRg(jTextrg.getText());
        controller.cliente.setTelefone(jTexttelefone.getText());
        controller.cliente.setEndereco(jTextendereco.getText());

        try {
            controller.salvar(controller.cliente);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "error: " + ex);
        } finally {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClienteGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroClienteGUI dialog = new CadastroClienteGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncadastrar;
    private javax.swing.JButton btnlimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JFormattedTextField jTextcpf;
    private javax.swing.JTextField jTextendereco;
    private javax.swing.JFormattedTextField jTextrg;
    private javax.swing.JFormattedTextField jTexttelefone;
    private javax.swing.JLabel lbObrigatorio4;
    private javax.swing.JLabel lbObrigatorioCpf;
    private javax.swing.JLabel lbObrigatorioEndereco;
    private javax.swing.JLabel lbObrigatorioNome;
    private javax.swing.JLabel lbObrigatorioRg;
    private javax.swing.JLabel lbObrigatorioTel;
    // End of variables declaration//GEN-END:variables

    private void verificaCamposEmpty() {

        if ((jTextNome.getText().trim().length() > 0) || !(jTextNome.getText().trim().length() <= 4)) {
            if (!jTextcpf.getText().equals("   .   .   -  ")) {
                if (jTextendereco.getText().trim().length() > 0) {
                    if (!jTextrg.getText().trim().equals("-")) {
                        if (!jTexttelefone.getText().equals("(  )     -    ")) {
                            salvar();
                        } else {
                            lbObrigatorioTel.setVisible(true);
                        }
                    } else {
                        lbObrigatorioRg.setVisible(true);
                    }
                } else {
                    lbObrigatorioEndereco.setVisible(true);
                }
            } else {
                lbObrigatorioCpf.setVisible(true);
            }
        } else {
            lbObrigatorioNome.setVisible(true);
        }
    }

}
